---
language: python
sudo: required

services:
  - docker

env:
  - OS_VERSION=7
  - OS_VERSION=6

before_install:
  - sudo docker pull centos:${OS_VERSION}

install:
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/yum-plugin-priorities:ro --name centos-${OS_VERSION} centos:${OS_VERSION} sleep 300
  - sudo docker exec centos-${OS_VERSION} yum -y install epel-release
  - sudo docker exec centos-${OS_VERSION} yum -y install ansible

script:
  # Check syntax of ansible playbook
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/yum-plugin-priorities/tests/test.yml --syntax-check
  # Run ansible playbook
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/yum-plugin-priorities/tests/test.yml

after_script:
  - sudo docker stop centos-${OS_VERSION}
